import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { ArrowLeft, Loader2, Sprout, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/hooks/use-auth";
import { fetchMyRoles } from "@/lib/db";
import { fetchAdminInbox, fetchMyAdminChat, sendAdminMessage, sendAdminReply, type AdminMessage } from "@/lib/admin-chat";
import { toast } from "sonner";

export const Route = createFileRoute("/chat")({ component: HelpUsGrowPage });
function HelpUsGrowPage(){const{user}=useAuth();const rolesQ=useQuery({queryKey:["roles",user?.id],queryFn:()=>fetchMyRoles(user!.id),enabled:!!user});const isAdmin=useMemo(()=>rolesQ.data?.includes("admin")??false,[rolesQ.data]);if(!user)return <div className="min-h-screen grid place-items-center bg-background p-4 pb-24"><Card className="max-w-sm p-6 text-center space-y-4"><Sprout className="h-8 w-8 mx-auto text-primary"/><h1 className="font-semibold">Help Us Grow</h1><p className="text-sm text-muted-foreground">Sign in to send an idea or suggestion for Grow Cambodia.</p><Link to="/auth"><Button>Sign in</Button></Link></Card></div>;if(rolesQ.isLoading)return <div className="min-h-screen grid place-items-center pb-24"><Loader2 className="h-6 w-6 animate-spin text-primary"/></div>;return isAdmin?<AdminInbox adminId={user.id}/>:<MemberSuggestions userId={user.id}/>}
function MemberSuggestions({userId}:{userId:string}){const qc=useQueryClient();const[body,setBody]=useState("");const messagesQ=useQuery({queryKey:["admin-chat",userId],queryFn:()=>fetchMyAdminChat(userId),refetchInterval:15000});const sendMut=useMutation({mutationFn:()=>sendAdminMessage(userId,body),onSuccess:()=>{setBody("");qc.invalidateQueries({queryKey:["admin-chat",userId]})},onError:(e:any)=>toast.error(e?.message??"Could not send suggestion")});return <ChatShell title="Help Us Grow"><Card className="p-5 space-y-3"><div className="flex items-center gap-2 text-primary"><Sprout className="h-5 w-5"/><h1 className="font-semibold text-lg">We want Kampot to grow — literally.</h1></div><p className="text-sm">Help us grow this app, grow more food, share local farming knowledge, and build a stronger farming community in Kampot and across Cambodia.</p><p className="text-sm text-muted-foreground">Have an idea? Found a problem? Want a feature? Know something that could help local growers? Send us your suggestion. Every idea helps us grow.</p></Card><MessageThread messages={messagesQ.data??[]} loading={messagesQ.isLoading}/><Composer value={body} onChange={setBody} placeholder="Share your idea or suggestion…" pending={sendMut.isPending} onSend={()=>body.trim()&&sendMut.mutate()}/></ChatShell>}
function AdminInbox({adminId}:{adminId:string}){const qc=useQueryClient();const[selectedUserId,setSelectedUserId]=useState<string|null>(null);const[body,setBody]=useState("");const inboxQ=useQuery({queryKey:["admin-inbox"],queryFn:fetchAdminInbox,refetchInterval:15000});const conversations=inboxQ.data??[];const active=conversations.find(c=>c.userId===selectedUserId)??conversations[0]??null;const replyMut=useMutation({mutationFn:async()=>{if(!active)throw new Error("Choose a conversation");return sendAdminReply(active.userId,adminId,body)},onSuccess:()=>{setBody("");qc.invalidateQueries({queryKey:["admin-inbox"]})},onError:(e:any)=>toast.error(e?.message??"Could not send reply")});return <ChatShell title="Suggestion Inbox">{conversations.length===0?<Card className="p-6 text-center text-sm text-muted-foreground">No community suggestions yet.</Card>:<><div className="flex gap-2 overflow-x-auto pb-1">{conversations.map(c=><button key={c.userId} onClick={()=>setSelectedUserId(c.userId)} className={`shrink-0 rounded-full border px-3 py-2 text-sm ${active?.userId===c.userId?"bg-primary text-primary-foreground border-primary":"bg-background"}`}>{c.displayName}</button>)}</div><Card className="p-3"><p className="text-sm font-medium">{active?.displayName}</p><p className="text-[11px] text-muted-foreground">Community suggestion / feedback</p></Card><MessageThread messages={active?.messages??[]} loading={inboxQ.isLoading}/><Composer value={body} onChange={setBody} placeholder={`Reply to ${active?.displayName??"member"}…`} pending={replyMut.isPending} onSend={()=>body.trim()&&active&&replyMut.mutate()}/></>}</ChatShell>}
function ChatShell({title,children}:{title:string;children:React.ReactNode}){return <div className="min-h-screen bg-background pb-28"><header className="sticky top-0 z-30 border-b bg-background/95 backdrop-blur"><div className="max-w-2xl mx-auto h-14 px-4 flex items-center justify-between"><Link to="/" className="flex items-center gap-2 text-sm font-medium"><ArrowLeft className="h-4 w-4"/> Community</Link><div className="flex items-center gap-2 font-semibold text-primary"><Sprout className="h-4 w-4"/> {title}</div></div></header><main className="max-w-2xl mx-auto px-4 py-4 space-y-4">{children}</main></div>}
function MessageThread({messages,loading}:{messages:AdminMessage[];loading:boolean}){return <div className="space-y-2 min-h-[35vh]">{loading&&<p className="text-sm text-muted-foreground text-center py-8">Loading…</p>}{messages.map(m=><div key={m.id} className={`flex ${m.sender_role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[82%] rounded-2xl px-4 py-2 text-sm ${m.sender_role==="user"?"bg-primary text-primary-foreground rounded-br-md":"bg-muted rounded-bl-md"}`}><p className="whitespace-pre-wrap">{m.body}</p><p className={`text-[10px] mt-1 ${m.sender_role==="user"?"text-primary-foreground/70":"text-muted-foreground"}`}>{m.sender_role==="admin"?"Grow Cambodia · ":""}{new Date(m.created_at).toLocaleString()}</p></div></div>)}{!loading&&messages.length===0&&<p className="text-sm text-muted-foreground text-center py-8">Your suggestions and our replies will appear here.</p>}</div>}
function Composer({value,onChange,placeholder,pending,onSend}:{value:string;onChange:(v:string)=>void;placeholder:string;pending:boolean;onSend:()=>void}){return <div className="sticky bottom-20 bg-background pt-2"><Card className="p-3 flex gap-2 items-end"><Textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} rows={2} maxLength={2000}/><Button size="icon" onClick={onSend} disabled={pending||!value.trim()} aria-label="Send suggestion">{pending?<Loader2 className="h-4 w-4 animate-spin"/>:<Send className="h-4 w-4"/>}</Button></Card></div>}
