import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { Heart, MessageCircle, MapPin, ImageIcon, Share2, Sparkles, BadgeCheck, Pin, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/hooks/use-auth";
import { toggleLike, fetchMyLikes, fetchComments, addComment, togglePinComment, fetchMyRoles, communityPostLabel, type FeedItem, type CommentRow } from "@/lib/db";
import { toast } from "sonner";
import { PhotoLightbox } from "./photo-lightbox";
import { ShareMenu } from "./share-menu";
import { analyzeUpdate } from "@/lib/analyze-update.functions";
import { formatDMY, formatRelativeAge } from "@/lib/date-format";

const STAGE_COLORS:Record<string,string>={"soil preparation":"bg-stone-100 text-stone-800","seed/planting":"bg-amber-100 text-amber-800",seeding:"bg-amber-100 text-amber-800",germination:"bg-lime-100 text-lime-800",transplant:"bg-emerald-100 text-emerald-800",vegetative:"bg-green-100 text-green-800",flowering:"bg-pink-100 text-pink-800",fruiting:"bg-orange-100 text-orange-800",harvest:"bg-yellow-100 text-yellow-800"};

export function UpdateCard({item,compact}:{item:FeedItem;compact?:boolean}){
 const {user}=useAuth();const qc=useQueryClient();const[showComments,setShowComments]=useState(false);const[lightbox,setLightbox]=useState<number|null>(null);
 const{data:myLikes}=useQuery({queryKey:["mylikes",user?.id,item.id],queryFn:()=>user?fetchMyLikes(user.id,[item.id]):Promise.resolve(new Set<string>()),enabled:!!user});const liked=myLikes?.has(item.id)??false;
 const likeMut=useMutation({mutationFn:()=>{if(!user)throw new Error("Sign in to like");return toggleLike(item.id,user.id)},onSuccess:()=>{qc.invalidateQueries({queryKey:["feed"]});qc.invalidateQueries({queryKey:["timeline"]});qc.invalidateQueries({queryKey:["mylikes"]})},onError:(e:any)=>toast.error(e.message)});
 const analyzeFn=useServerFn(analyzeUpdate);const analyzeMut=useMutation({mutationFn:()=>analyzeFn({data:{updateId:item.id}}),onSuccess:()=>{toast.success("AI analysis added");setShowComments(true);qc.invalidateQueries({queryKey:["comments",item.id]})},onError:(e:any)=>toast.error(e.message??"Analysis failed")});
 const stageColor=STAGE_COLORS[item.growth_stage.toLowerCase()]??"bg-secondary text-secondary-foreground";const farm=item.plant_logs?.farms;const log=item.plant_logs;const typeLabel=communityPostLabel(item.post_type);const shareUrl=typeof window!=="undefined"?`${window.location.origin}/log/${log?.id??""}#u-${item.id}`:`/log/${log?.id??""}`;const shareText=`${typeLabel}: ${log?.crop_type??"Farming"} on Grow Cambodia`;
 return <Card id={`u-${item.id}`} className="overflow-hidden scroll-mt-20">
  <div className="p-4 pb-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2 text-sm"><span className="font-semibold truncate">{item.profiles?.display_name??"Farmer"}</span><span className="text-muted-foreground">·</span><span className="text-muted-foreground text-xs">{formatRelativeAge(item.created_at)} · {formatDMY(item.created_at)}</span></div><div className="mt-1"><span className="inline-flex rounded-full bg-primary/10 px-2 py-0.5 text-[11px] font-semibold text-primary">{typeLabel}</span></div>{!compact&&log&&<Link to="/log/$logId" params={{logId:log.id}} className="text-sm text-primary hover:underline block truncate mt-1">{log.title} · {log.crop_type}</Link>}{farm&&<div className="text-xs text-muted-foreground flex items-center gap-1 mt-0.5 truncate"><MapPin className="h-3 w-3"/> {farm.name}</div>}</div>{item.post_type==="growth"&&<span className={`text-xs font-medium px-2 py-1 rounded-full whitespace-nowrap ${stageColor}`}>{item.growth_stage}</span>}</div></div>
  {item.image_urls.length>0&&<div className={`grid gap-0.5 ${item.image_urls.length===1?"grid-cols-1":"grid-cols-2"}`}>{item.image_urls.slice(0,4).map((url,i)=><button key={i} type="button" onClick={()=>setLightbox(i)} className="block w-full aspect-square bg-muted overflow-hidden"><img src={url} alt="" loading="lazy" className="w-full h-full object-cover hover:opacity-95 transition"/></button>)}</div>}
  {item.notes&&<p className="px-4 py-3 text-sm whitespace-pre-wrap">{item.notes}</p>}
  <div className="px-2 pb-2 flex items-center gap-0.5 flex-wrap"><Button variant="ghost" size="sm" onClick={()=>likeMut.mutate()} className={liked?"text-red-600":""}><Heart className={`h-4 w-4 ${liked?"fill-current":""} ${item.likes>0?"mr-1.5":""}`}/>{item.likes>0?item.likes:null}</Button><Button variant="ghost" size="sm" onClick={()=>setShowComments(v=>!v)}><MessageCircle className={`h-4 w-4 ${item.comment_count>0?"mr-1.5":""}`}/>{item.comment_count>0?item.comment_count:null}</Button><ShareMenu url={shareUrl} text={shareText} trigger={<><Share2 className="h-4 w-4 mr-1.5"/>Share</>}/>{user&&<Button variant="ghost" size="sm" onClick={()=>analyzeMut.mutate()} disabled={analyzeMut.isPending} title="Ask the AI agronomist"><Sparkles className="h-4 w-4 mr-1.5 text-primary"/>{analyzeMut.isPending?"Analyzing…":"Analyze"}</Button>}{item.image_urls.length>4&&<span className="text-xs text-muted-foreground ml-auto pr-3 flex items-center gap-1"><ImageIcon className="h-3 w-3"/> +{item.image_urls.length-4}</span>}</div>
  {!compact&&log&&<div className="border-t px-4 py-2 flex items-center justify-between text-xs text-muted-foreground"><Link to="/log/$logId" params={{logId:log.id}} className="hover:text-primary flex items-center gap-1">View full timeline <ChevronRight className="h-3 w-3"/></Link></div>}
  {showComments&&<CommentsSection updateId={item.id} logOwnerId={log?.user_id}/>} {lightbox!==null&&<PhotoLightbox images={item.image_urls} startIndex={lightbox} onClose={()=>setLightbox(null)}/>} </Card>
}

function CommentsSection({updateId,logOwnerId}:{updateId:string;logOwnerId?:string}){const{user}=useAuth();const qc=useQueryClient();const[body,setBody]=useState("");const{data:comments,isLoading}=useQuery({queryKey:["comments",updateId],queryFn:()=>fetchComments(updateId)});const{data:roles}=useQuery({queryKey:["roles",user?.id],queryFn:()=>user?fetchMyRoles(user.id):Promise.resolve([]),enabled:!!user});const canPin=roles?.some(r=>r==="admin"||r==="moderator")??false;const isAgronomist=roles?.includes("agronomist")??false;const addMut=useMutation({mutationFn:()=>{if(!user)throw new Error("Sign in to comment");if(!body.trim())throw new Error("Write a comment first");return addComment(updateId,body.trim(),user.id,user.email?.split("@")[0]??"Farmer",{isAgronomist})},onSuccess:()=>{setBody("");qc.invalidateQueries({queryKey:["comments",updateId]});qc.invalidateQueries({queryKey:["feed"]})},onError:(e:any)=>toast.error(e.message)});const pinMut=useMutation({mutationFn:({id,pinned}:{id:string;pinned:boolean})=>togglePinComment(id,pinned),onSuccess:()=>qc.invalidateQueries({queryKey:["comments",updateId]})});return <div className="border-t bg-muted/20 p-4 space-y-3">{isLoading?<p className="text-xs text-muted-foreground">Loading comments…</p>:(comments??[]).map((c:CommentRow)=><div key={c.id} className={`rounded-md p-3 text-sm ${c.is_ai?"bg-primary/5 border border-primary/20":"bg-background border"}`}><div className="flex items-center gap-1.5 mb-1"><span className="font-medium">{c.author_name}</span>{c.is_ai&&<BadgeCheck className="h-3.5 w-3.5 text-primary"/>}{c.pinned&&<Pin className="h-3 w-3 text-primary"/>}<span className="ml-auto text-[10px] text-muted-foreground">{formatDMY(c.created_at)}</span></div><div className="whitespace-pre-wrap text-sm">{c.body}</div>{canPin&&!c.is_ai&&<button className="text-[10px] text-primary mt-2" onClick={()=>pinMut.mutate({id:c.id,pinned:!c.pinned})}>{c.pinned?"Unpin":"Pin helpful reply"}</button>}</div>)}{user?<div className="flex gap-2"><Textarea rows={2} value={body} onChange={e=>setBody(e.target.value)} placeholder={logOwnerId===user.id?"Reply or add an update…":"Share advice or ask a question…"}/><Button size="sm" onClick={()=>addMut.mutate()} disabled={addMut.isPending}>Reply</Button></div>:<p className="text-xs text-muted-foreground">Sign in to join the discussion.</p>}</div>}
