/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as MyFarmsRouteImport } from './routes/my-farms'
import { Route as IdentifyRouteImport } from './routes/identify'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogLogIdRouteImport } from './routes/log.$logId'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const MyFarmsRoute = MyFarmsRouteImport.update({
  id: '/my-farms',
  path: '/my-farms',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentifyRoute = IdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogLogIdRoute = LogLogIdRouteImport.update({
  id: '/log/$logId',
  path: '/log/$logId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/identify': typeof IdentifyRoute
  '/my-farms': typeof MyFarmsRoute
  '/review': typeof ReviewRoute
  '/log/$logId': typeof LogLogIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/identify': typeof IdentifyRoute
  '/my-farms': typeof MyFarmsRoute
  '/review': typeof ReviewRoute
  '/log/$logId': typeof LogLogIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/identify': typeof IdentifyRoute
  '/my-farms': typeof MyFarmsRoute
  '/review': typeof ReviewRoute
  '/log/$logId': typeof LogLogIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/identify' | '/my-farms' | '/review' | '/log/$logId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/identify' | '/my-farms' | '/review' | '/log/$logId'
  id: '__root__' | '/' | '/auth' | '/identify' | '/my-farms' | '/review' | '/log/$logId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  IdentifyRoute: typeof IdentifyRoute
  MyFarmsRoute: typeof MyFarmsRoute
  ReviewRoute: typeof ReviewRoute
  LogLogIdRoute: typeof LogLogIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-farms': {
      id: '/my-farms'
      path: '/my-farms'
      fullPath: '/my-farms'
      preLoaderRoute: typeof MyFarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identify': {
      id: '/identify'
      path: '/identify'
      fullPath: '/identify'
      preLoaderRoute: typeof IdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log/$logId': {
      id: '/log/$logId'
      path: '/log/$logId'
      fullPath: '/log/$logId'
      preLoaderRoute: typeof LogLogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  IdentifyRoute: IdentifyRoute,
  MyFarmsRoute: MyFarmsRoute,
  ReviewRoute: ReviewRoute,
  LogLogIdRoute: LogLogIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
